project:
  type: website
  output-dir: docs

website:
  title: "国際公共政策学"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "導入"
        contents: 
          - index.qmd
          - international_society.qmd
      - section: "国際安全保障"
        contents: 
          - causes_of_war.qmd
          - power_peace.qmd
          - liberal_peace.qmd
      - section: "国際政治経済"
      - section: "越境的政治"

format:
  html:
    theme: lumen
    include-in-header:
      - analytics.html
    mainfont: Noto Sans CJK JP DemiLight
    toc: true
    number-sections: true
    reference-location: margin
    # fig-cap-location: margin
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
  pdf:
    pdf-engine: latexmk
    pdf-engine-opt: "-xelatex"
    latex-output-dir: pdf
    latex-auto-install: false
    documentclass: bxjsarticle
    classoption:
      - xelatex
      - ja=standard
    include-in-header: 
      text: |
        \renewcommand{\thefootnote}{\arabic{footnote}}
    mainfont: Noto Serif CJK JP
    mainfontoptions: 
      - BoldFont=Noto Sans CJK JP
    number-sections: true
    fig-pos: "htpb"
    linkcolor: NavyBlue
    citecolor: NavyBlue
    urlcolor: NavyBlue
    cite-method: natbib
    biblio-config: true
    biblio-style: jecon

bibliography: references.bib
lang: ja

