---
title: "はじめに"
subtitle: "国際公共政策学"
author: "土井翔平"
date: today
---

[土井翔平](https://shohei-doi.github.io)が担当する[北海道大学公共政策大学院 (HOPS)](https://www.hops.hokudai.ac.jp/)の国際公共政策学の講義レジュメです。受講生はこのサイトもしくはpdf版を参照して、授業に望んでください。

## 目標

国際公共政策学とは？

- 戦争や貿易紛争、環境破壊など様々な国際問題
- 国際問題は存在しない方が国々や人々は嬉しいはずなのに、解決できないのはなぜか？

$\leadsto$国際政治学・**国際関係論** (international relations: IR) を学ぶ^[日本では国際政治学という言葉が広く使われているが、世界的には国際関係論の方が使われている。]。

代表的な国際問題について、次の3つの問に焦点を当てる。

- 国際問題はなぜ生じるのか？（**原因**）
- 国際問題をどのように解決するのか？（**解決策**）
- 国際問題はなぜ解決できないのか？（**限界**）

様々な国や時代、あるいは国際問題に**共通する構造**に着目する。

- 例：医者による診断（原因の発見）と処方（解決策の提示）$\leadsto$様々な患者に共通する要因を見つける。
    - ロシアやウクライナのことを知らずして、ロシア・ウクライナ戦争を理解できるのか？

:::{.callout-warning}
## 地域研究や歴史研究

もちろん、特定の国や地域、時代によって国際政治のあり方は異なるし、それが重要でないという意味ではない。HOPSでは様々な地域に関する授業が開講されているので、それらも受講してもらいたい。

また、”一般人の知らない国際政治や外交の現場”のような話もしない（というよりできない）。それらは実務家の講演や回顧録などを参照してもらいたい。
:::

## トピック

国際問題は大きく2つ、あるいは3つに分けることができる。^[もちろん、特定のイシューは実際には特定の複数のカテゴリーにまたがっている。]

- **国際安全保障** (international security/security study)
    - 戦争の原因、安全保障政策（軍事力による平和、集団安全保障、民主的平和、商業的平和）、軍備管理・不拡散
- **国際政治経済** (international political economy)
    - 経済成長、貿易、金融・通貨
- **越境的政治** (transnational politics/issues)
    - 環境保護、人権保障、移民・難民、内戦・テロ、平和維持・構築

:::{.callout-warning}
## カバーできないトピック

全ての国際問題を扱うことはできないが、様々な国際問題を理解する上で役立つ概念、理論、思考法を身につけてもらえるように授業をする。
:::

## 授業の進め方

Moodleを参照すること。

## 参考書

特定の教科書を用いないが、自習のためにいくつかの参考書を紹介する。**国際関係論のテキストは多種多様なので、ぜひ読み比べて欲しい。**

- なにから読めばよいか分からない初学者の方は、まず @sunahara2020 や @sakamoto2020 など政治学の入門レベルの教科書の中の国際関係に関する箇所を読むことを勧める。その後、 @murata2023 など国際関係論の入門レベルの教科書を読むとよい。
- 身近な日本の話題から国際関係や国際法へ入門するものとして @sato2018 や @morikawa2016 などがある。
- 既に国際関係論を学んだことがある人は @nakanishi2013 や @yamakage2012 など が発展レベルの教科書としてある。また、発展レベルの政治学を扱う @kume2011 の国際関係に関する箇所も読むとよい。
- 国際関係の重要な知識をまとめたものとして @tanaka2010 は辞書的に使うことができる^[ただし、やや古いので注意。]。
- なお、この授業はアメリカの学部レベルの教科書である @frieden2019 をベースにしているため、国際関係論を本格的に学習したい人は挑戦することを勧める。

国際関係論を直接扱うものではないが、この授業を理解する上で重要な周辺知識に関する参考書も挙げておく。

- 国際関係を理解する上で国際政治史、国際法、比較政治の知識は不可欠である。これらについても多くのテキストがあるが、入り口としてそれぞれ @ogawa2018 、@tamada2022 、 @kubo2016 を紹介する。
- 国際関係の一つの見方としてゲーム理論^[ゲーム理論自体はミクロ経済学の一分野である。]がある。ゲーム理論を用いた政治学の入門レベルの教科書として @asako2018 がある。また、 @okada2020 はゲーム理論を用いた国際関係論のテキストである（ただし、やや難易度は高い）。

これらに加えて、[こちら](https://sdoi.notion.site/bc51220cd2c54100a75981e56123b235)で紹介している「国際問題に関する情報」なども関心に応じて参考とすること。

:::{.callout-warning}
## 引用方法

技術的な問題から、html版の講義ノートにおける引用方法は適切ではないので、**参考にしないこと**。学生便覧の「引用の仕方」を参照。
:::